const fs = require('fs');
const path = require('path');
const vm = require('vm');

const rootDir = path.join(__dirname, '..');

// Helper to load and parse TS generated files by stripping TypeScript types
function loadTSFile(filePath, exportName) {
  let content = fs.readFileSync(filePath, 'utf8');
  // Strip import statements
  content = content.replace(/import type\s+[\s\S]*?from\s+["'].*?["'];?/g, '');
  // Strip TS "as const" satisfies at the end of the file FIRST
  const match = content.match(/\}\s+as\s+const\s+satisfies/);
  if (match) {
    content = content.substring(0, match.index) + '}';
  }
  // Strip "satisfies Model<...>" or "satisfies ImagesModel<...>"
  content = content.replace(/\s+satisfies\s+[A-Za-z0-9_<>:"'-]+(?=,|\s|$)/g, '');
  content = content.replace(/\s+as\s+const/g, '');
  // Replace export const VAR = with global.VAR =
  content = content.replace(new RegExp(`export const ${exportName}\\s*=`), `global.${exportName} =`);
  
  const sandbox = { global: {} };
  vm.createContext(sandbox);
  try {
    vm.runInContext(content, sandbox);
  } catch (err) {
    console.error(`Error executing ${filePath}:`, err);
    throw err;
  }
  return sandbox.global[exportName];
}

const apiMap = {
  "openai-completions": "APIOpenAICompletions",
  "mistral-conversations": "APIMistralConversations",
  "openai-responses": "APIOpenAIResponses",
  "azure-openai-responses": "APIAzureOpenAIResponses",
  "openai-codex-responses": "APIOpenAICodexResponses",
  "anthropic-messages": "APIAnthropicMessages",
  "bedrock-converse-stream": "APIBedrockConverseStream",
  "google-generative-ai": "APIGoogleGenerativeAI",
  "google-vertex": "APIGoogleVertex"
};

const providerMap = {
  "amazon-bedrock": "ProviderAmazonBedrock",
  "anthropic": "ProviderAnthropic",
  "google": "ProviderGoogle",
  "google-vertex": "ProviderGoogleVertex",
  "openai": "ProviderOpenAI",
  "azure-openai-responses": "ProviderAzureOpenAIResponses",
  "openai-codex": "ProviderOpenAICodex",
  "deepseek": "ProviderDeepSeek",
  "github-copilot": "ProviderGitHubCopilot",
  "xai": "ProviderXAI",
  "groq": "ProviderGroq",
  "cerebras": "ProviderCerebras",
  "openrouter": "ProviderOpenRouter",
  "vercel-ai-gateway": "ProviderVercelAIGateway",
  "mistral": "ProviderMistral",
  "fireworks": "ProviderFireworks",
  "together": "ProviderTogether",
  "cloudflare-ai-gateway": "ProviderCloudflareAIGateway",
  "cloudflare-workers-ai": "ProviderCloudflareWorkersAI",
  "huggingface": "ProviderHuggingFace",
  "kimi-coding": "ProviderKimiCoding",
  "minimax": "ProviderMinimax",
  "minimax-cn": "ProviderMinimaxCN",
  "moonshotai": "ProviderMoonshotAI",
  "moonshotai-cn": "ProviderMoonshotAICN",
  "zai": "ProviderZAI",
  "opencode": "ProviderOpenCode",
  "opencode-go": "ProviderOpenCodeGo",
  "xiaomi": "ProviderXiaomi",
  "xiaomi-token-plan-cn": "ProviderXiaomiTokenPlanCN",
  "xiaomi-token-plan-ams": "ProviderXiaomiTokenPlanAMS",
  "xiaomi-token-plan-sgp": "ProviderXiaomiTokenPlanSGP"
};

function getAPIConst(api) {
  if (apiMap[api]) return apiMap[api];
  return `API(${JSON.stringify(api)})`;
}

function getProviderConst(provider) {
  if (providerMap[provider]) return providerMap[provider];
  return `Provider(${JSON.stringify(provider)})`;
}

function formatGoCost(cost) {
  if (!cost) return 'CostPerMillion{}';
  const inp = cost.input || 0;
  const out = cost.output || 0;
  const cr = cost.cacheRead || 0;
  const cw = cost.cacheWrite || 0;
  return `CostPerMillion{Input: ${inp}, Output: ${out}, CacheRead: ${cr}, CacheWrite: ${cw}}`;
}

function generateChatModels() {
  const modelsPath = path.join(rootDir, 'pi/packages/ai/src/models.generated.ts');
  const models = loadTSFile(modelsPath, 'MODELS');
  
  let goCode = `// Code generated by scripts/generate.js. DO NOT EDIT.
package ai

func GeneratedModels() []ModelDefinition {
\treturn []ModelDefinition{
`;

  // MODELS is a nested object: providerSlug -> modelId -> modelDef
  for (const providerSlug in models) {
    const providerModels = models[providerSlug];
    for (const modelId in providerModels) {
      const m = providerModels[modelId];
      
      const apiConst = getAPIConst(m.api);
      const providerConst = getProviderConst(m.provider);
      const name = m.id; // Wait! The ID in the map is actually what `rho` expects as the model Name (e.g. "gpt-4o")
      const displayName = m.name || '';
      const baseUrl = m.baseUrl || '';
      const contextWindow = m.contextWindow || 0;
      const maxTokens = m.maxTokens || 0;
      const reasoning = m.reasoning ? 'true' : 'false';
      
      // format inputs slice
      let inputsGo = '[]string{}';
      if (m.input && m.input.length > 0) {
        inputsGo = `[]string{${m.input.map(i => JSON.stringify(i)).join(', ')}}`;
      }
      
      const costGo = formatGoCost(m.cost);
      
      // format thinkingLevelMap
      let mapGo = 'nil';
      if (m.thinkingLevelMap && Object.keys(m.thinkingLevelMap).length > 0) {
        const parts = [];
        for (const k in m.thinkingLevelMap) {
          const val = m.thinkingLevelMap[k];
          if (val === null) {
            parts.push(`"${k}": nil`);
          } else {
            parts.push(`"${k}": pointerToString(${JSON.stringify(val)})`);
          }
        }
        mapGo = `map[string]*string{${parts.join(', ')}}`;
      }
      
      // format headers
      let headersGo = 'nil';
      if (m.headers && Object.keys(m.headers).length > 0) {
        const parts = [];
        for (const k in m.headers) {
          parts.push(`"${k}": ${JSON.stringify(m.headers[k])}`);
        }
        headersGo = `map[string]string{${parts.join(', ')}}`;
      }
      
      // Generate the ModelDefinition struct literal
      goCode += `\t\t{
\t\t\tAPI:            ${apiConst},
\t\t\tProvider:       ${providerConst},
\t\t\tName:           ${JSON.stringify(name)},
\t\t\tDisplayName:    ${JSON.stringify(displayName)},
\t\t\tBaseURL:        ${JSON.stringify(baseUrl)},
\t\t\tContextWindow:  ${contextWindow},
\t\t\tMaxTokens:      ${maxTokens},
\t\t\tReasoning:      ${reasoning},
\t\t\tInput:          ${inputsGo},
\t\t\tCost:           ${costGo},
\t\t\tThinkingMap:    ${mapGo},
\t\t\tHeaders:        ${headersGo},
\t\t},\n`;
    }
  }

  goCode += `\t}
}
`;

  const outputPath = path.join(rootDir, 'pkg/ai/models.generated.go');
  fs.writeFileSync(outputPath, goCode, 'utf8');
  console.log(`Generated chat models file: ${outputPath}`);
}

function generateImageModels() {
  const imagesPath = path.join(rootDir, 'pi/packages/ai/src/image-models.generated.ts');
  const imageModels = loadTSFile(imagesPath, 'IMAGE_MODELS');
  
  let goCode = `// Code generated by scripts/generate.js. DO NOT EDIT.
package ai

func GeneratedImageModels() []ImageModelDefinition {
\treturn []ImageModelDefinition{
`;

  // IMAGE_MODELS is nested: providerSlug -> modelId -> modelDef
  for (const providerSlug in imageModels) {
    const providerModels = imageModels[providerSlug];
    for (const modelId in providerModels) {
      const m = providerModels[modelId];
      
      const apiConst = `API(${JSON.stringify(m.api)})`;
      const providerConst = getProviderConst(m.provider);
      const name = m.id;
      const displayName = m.name || '';
      const baseUrl = m.baseUrl || '';
      
      let inputsGo = '[]string{}';
      if (m.input && m.input.length > 0) {
        inputsGo = `[]string{${m.input.map(i => JSON.stringify(i)).join(', ')}}`;
      }
      
      let outputsGo = '[]string{}';
      if (m.output && m.output.length > 0) {
        outputsGo = `[]string{${m.output.map(o => JSON.stringify(o)).join(', ')}}`;
      }
      
      const costGo = formatGoCost(m.cost);
      
      goCode += `\t\t{
\t\t\tAPI:            ${apiConst},
\t\t\tProvider:       ${providerConst},
\t\t\tName:           ${JSON.stringify(name)},
\t\t\tDisplayName:    ${JSON.stringify(displayName)},
\t\t\tBaseURL:        ${JSON.stringify(baseUrl)},
\t\t\tInput:          ${inputsGo},
\t\t\tOutput:         ${outputsGo},
\t\t\tCost:           ${costGo},
\t\t},\n`;
    }
  }

  goCode += `\t}
}
`;

  const outputPath = path.join(rootDir, 'pkg/ai/image_models.generated.go');
  fs.writeFileSync(outputPath, goCode, 'utf8');
  console.log(`Generated image models file: ${outputPath}`);
}

try {
  generateChatModels();
  generateImageModels();
} catch (e) {
  console.error("Generation failed:", e);
  process.exit(1);
}
